openapi: 3.0.2
info:
   title: 存款相關
   version: "2.0"
servers:
   - url: https://bankeesit.feib.com.tw/webctl/api/deposit
paths:
  /sendAcctTxDtl:
      post:
         summary: email發送交易明細檔(數位存摺)
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/QueryAcctTxDtlRq"
         responses:
            "200":
               description: OK
               content:
                  application/json;charset=UTF-8:
                     schema:
                        type: string
                        example: "send email success"
components:
   schemas:
      QueryAcctTxDtlRq:
         type: object
         properties:
            actNo:
               type: string
               description: 帳號
               example: "00100100063106"
            tranType:
               type: string
               description: 摘要代碼 1:跨轉、2:ATM、3:存款息、4:薪轉、5:付款儲存、6:自動扣繳, 可多筆
               example: "1,2,3"
            dataMonth:
               type: string
               description: 起始月份, 預設為最接近月底的日期為起始索引
               example: "202104"
            startDate:
               type: string
               description: 交易日期起日
               example: "20210101"
            endDate:
               type: string
               description: 交易日期迄日
               example: "20210713"
            startIndex:
               type: number
               description: 指定起始筆數
               example: 150
            direct:
               type: number
               description: 方向性.1:正向(新~舊)、2:反向(舊~新)、0:雙向方向性
               example: 1
            keyword:
               type: string
               description: 文字檢索條件
               example: "退款"
            fileType:
               type: number
               description: 下載檔案類型, 1:PDF, 2:EXCEL
               example: 1
            pdfTemplateType:
               type: number
               description: Pdf版型, 1:只有封面(可參考PdfTemplateType), 2:只有內容, 3:完整內容
               example: 3