openapi: 3.0.2
info:
  title: 設定相關
  version: "2.0"
servers:
  - url: https://bankeesit.feib.com.tw/webctl/api/setting
paths:
  /member/updateInfo:
    post:
      summary: 更新使用者暱稱
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateMemberInfoRq"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse<String>"
  /member/getInfo:
    post:
      summary: 取得使用者暱稱
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../common.yml#/components/schemas/CustIdRq"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse<GetMemberInfoRs>"
components:
  schemas:
    UpdateMemberInfoRq:
      type: object
      properties:
        custId:
          type: string
          description: 身分證字號
          example: A146076930
        nickName:
          type: string
          description: 暱稱
          example: 這是會員暱稱
    ApiResponse<String>:
      allOf:
        - $ref: ../common.yml#/components/schemas/ApiResponse
        - type: object
          properties:
            data:
              type: string
              description: isg token
              example: 037cc03dd-3091-e410-7f4d-d8e9872e15e003097
    ApiResponse<GetMemberInfoRs>:
      allOf: # combines ApiResponse and data
        - $ref: "../common.yml#/components/schemas/ApiResponse"
        - type: object
          properties:
            encData:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: 名稱
                    example: 測試人員
                  nickName:
                    type: string
                    description: 暱稱
                    example: 開發者00
                  uuid:
                    type: string
                    description: 會員唯一識別碼(guid)
                    example: BE6CCE647BD53D92E0531AA5300A5089